export const productArray = [
  {
    name: "AC: Valhalla",
    image: "images/indeximg/acvalhallaartcomp.jpg",
    category: "Action adventure",
    id: "1",
    price: 65.99,
    tag: "Trending",
  },
  {
    name: "The last of us II",
    image: "images/indeximg/tla2artcomp.jpg",
    category: "Action-adventure",
    id: "2",
    price: 49.99,
    tag: "Trending",
  },
  {
    name: "Ghost OT",
    image: "images/indeximg/ghostsoftsushimacomp.jpg",
    category: "Action-adventure",
    id: "3",
    price: 59.99,
    tag: "Trending",
  },
  {
    name: "Fall guys",
    image: "images/indeximg/fallcomp.jpg",
    category: "Action-adventure",
    id: "4",
    price: 9.51,
    tag: "Trending",
  },
  {
    name: "Guitar Hero 3",
    image: "images/indeximg/gh3comp.jpg",
    category: "Action-adventure",
    id: "5",
    price: 69.99,
    tag: "Trending",
  },
  {
    name: "Super Mario 64",
    image: "images/indeximg/sm64artcomp.jpg",
    category: "Action-adventure platformer",
    id: "6",
    price: 13.65,
    tag: "Trending",
  },
  {
    name: "Call of Duty Black Ops Cold War",
    image: "images/indeximg/coldwarsmall.jpg",
    category: "Action adventure",
    id: "7",
    price: 89.99,
    tag: "pre-order",
  },
  {
    name: "Cyberpunk 2077",
    image: "images/indeximg/cyberpunkcol1.jpg",
    category: "Action-adventure",
    id: "8",
    price: 69.99,
    tag: "pre-order",
  },
  {
    name: "2k21 Mamba Forever Edition",
    image: "images/indeximg/2k21coversmall.jpg",
    category: "Action-adventure",
    id: "9",
    price: 99.99,
    tag: "pre-order",
  },
  {
    name: "Gears Tactics",
    image: "images/indeximg/gearssmall.jpg",
    category: "Action-adventure",
    id: "10",
    price: 59.99,
    tag: "pre-order",
  },
  {
    name: "Horizon Zero Dawn",
    image: "images/indeximg/Horizoncol2.jpg",
    category: "Action adventure",
    id: "11",
    price: 30.71,
    oldPrice: 59.12,
    decrease: "-63%",
    tag: "near-new",
  },
  {
    name: "Call of Duty Black Ops III",
    image: (src = "images/indeximg/CodBO3small.jpg"),
    category: "Action-adventure",
    id: "12",
    price: 26.21,
    oldPrice: 70.94,
    decrease: "-63%",
    tag: "near-new",
  },
  {
    name: "Dead by Daylight",
    image: "images/indeximg/deadbydaylightsmall.jpg",
    category: "Action-adventure",
    id: "13",
    price: 7.38,
    oldPrice: 23.64,
    decrease: "-68%",
    tag: "near-new",
  },
  {
    name: "Overwatch",
    image: "images/indeximg/OVERWATCHsmall.jpg",
    category: "Action-adventure",
    id: "14",
    price: 18.06,
    oldPrice: 59.12,
    decrease: "-63%",
    tag: "near-new",
  },
  {
    name: "Minecraft: Windows 10 Edition (PC)",
    image: "images/indeximg/minecraftsmall.jpg",
    category: "Action adventure",
    id: "15",
    price: 89.99,
    tag: "best",
  },
  {
    name: "Call of Duty Modern Warfare 2",
    image: "images/indeximg/mw2coversmall.jpg",
    category: "Action-adventure",
    id: "16",
    price: 13.37,
    tag: "best",
  },
  {
    name: "Grand Theft Auto V",
    image: "images/indeximg/CoverArt-GTAVsmall.jpg",
    category: "Action-adventure",
    id: "17",
    price: 27.62,
    tag: "best",
  },
  {
    name: "The Elder Scrolls V",
    image: "images/indeximg/SKYRIMcoversmall.jpg",
    category: "Action-adventure",
    id: "18",
    price: 33.57,
    tag: "best",
  },
];
